### ISSUE TITLE
Can't create localization file

### ISSUE THREAD

**Issue by MarceloPrado** [bitomule/RelativeFormatter#1]
I don't know how to create a new localization file on this project, but I'm attaching to this issue a new language, hoping you can add to the final project. Sorry for that... Thanks!
Language: portuguese (brazillian)

/\* A single strings file, whose title is specified in your preferences schema. The strings files provide the localized content to display to the user for each of your preferences. */

//Year
"yearsago"= "%1$lu anos atrás";
"yearago"= "1 ano atrás";

"yearsahead"= "em %1$lu anos";
"yearahead"= "em 1 ano";

//Month
"monthsago"= "%1$lu meses atrás";
"monthago"= "1 mês atrás";

"monthsahead"= "em %1$lu meses";
"monthahead"= "em 1 mês";

//Week
"weeksago"= "%1$lu semanas atrás";
"weekago"= "1 semana atrás";

"weeksahead"= "em %1$lu semanas";
"weekahead"= "em 1 semana";

//Day
"daysago"= "%1$lu dias atrás";
"dayago"= "1 dia atrás";

"dayago-idiomatic"= "ontem";

"daysahead"= "em %1$lu dias";
"dayahead"= "em 1 dia";

"dayahead-idiomatic"= "amanhã";

//Hour
"hoursago"= "%1$lu horas atrás";
"hourago"= "1 hora atrás";

"hoursahead"= "em %1$lu horas";
"hourahead"= "em 1 hora";

//Minute
"minutesago"= "%1$lu minutos atrás";
"minuteago"= "1 minuto atrás";

"minutesahead"= "em %1$lu minutos";
"minuteahead"= "em 1 minuto";

//Second
"secondsago"= "%1$lu segundos atrás";
"secondago"= "1 segundos atrás";

"secondsago-idiomatic"= "a poucos segundos atrás";

"secondsahead"= "em %1$lu segundos";
"secondahead"= "em 1 segundo";

"secondsahead-idiomatic"= "em poucos segundos";

"now"="agora";

//Precision

"thisyear"="este ano";
"thismonth"="este mês";
"thisweek"="este semana";
"today"="hoje";
"thishour"="a menos de uma hora";
"thisminute"="a menos de um minuto";

**Comment by bitomule** [comment]
Hi, you can create a PR including the strings file in the project, that would be great and it's really easy.

**Comment by bitomule** [comment]
Accepted your pull request, sorry it taked me too much time.
