### ISSUE TITLE
xcode 7.0 and swift2   ıssue 

### ISSUE THREAD

**Issue by idrisyildiz7** [bitomule/RelativeFormatter#3]
var localizedString = NSLocalizedString(key, tableName: "RelativeFormatter", bundle: NSBundle(path: NSBundle(forClass: LocalizationHelper.self).resourcePath!.stringByAppendingPathComponent("RelativeFormatter.bundle"))!, value: "", comment: "") 

stringByAppendingPathComponent is  unavailable for swit2 ?

**Comment by idrisyildiz7** [comment]
NSCalendarUnit' has no member 'CalendarUnitMinute'

**Comment by bitomule** [comment]
Thanks @idrisyildiz7, I'll update to swift2 asap (hope this week)

**Comment by bitomule** [comment]
@idrisyildiz7 pushed update with swift 2 support. Thanks!
