### ISSUE TITLE
Library imported but functions are not available ?

### ISSUE THREAD

**Issue by fadylateef** [bitomule/RelativeFormatter#9]
I'm using Swift 3 , Xcode 8 and OS Sierra.
after importing the library at podfile and installing it and opening from workspace file 
Date.relativeFormatter() is not available

**Comment by bitomule** [comment]
You have to use Date().relativeFormatted(). relativeFormatted is a function in a Date instance, not Date class itself.

**Comment by fadylateef** [comment]
I understand , I forgot to import Relative Formatter Module. 
But you did not mention that :)

**Comment by bitomule** [comment]
Ups, sorry. I didn't understand well your issue. Great you found the issue :)

**Comment by fadylateef** [comment]
Nope , thanks goes back to you for that great library :) keep it up 👍
